# Site settings
title: "Water's gateway to heaven"
email: 
description: "Vienna Science and Technology Fund (WWTF) funded project LS19-013"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://waters-gateway.github.io # the base hostname & protocol for your site
# github_username:  gtrancourt
# twitter_username: GTRancourt

# Build settings
markdown: kramdown

# Other options
timezone: Europe/Vienna
permalink: /:year/:month/:day/:title.html
excerpt_separator: "<!--more-->"

# Language preferences - polyglot
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

exclude: [vendor]

#Post settings
future: true

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""